1 plugin saving job description
project-turbocharger/turbocharger-plugin pull request #2
Opened 2023-06-01 21:02 UTC by jekiquin

DoD:

Target LinkedIn and Indeed (and maybe Otta)

Capture UserID (optional for now), Company, Job Title, Description, Job Board Source, URL

Additional context:

1. Added husky, lint-staged and eslint for code quality

2023-06-02 01:42 UTC, yhus requested changes

2023-06-02 01:42 UTC, yhus commented on plugin/manifest.json
> +  "name": "Virgl Extensions",
Turbocharger

2023-06-02 01:42 UTC, yhus commented on plugin/scripts/utils/queries.js
> +  // return Promise.reject(null)
Remove commented out code

2023-06-02 01:42 UTC, yhus commented on plugin/scripts/utils/jobBoard.js
> +  console.log('Virgl', response)
Necessary?

2023-06-02 01:42 UTC, yhus commented on plugin/scripts/utils/helper.js
> +        console.log('Virgl', req.payload)
Are these necessary? Can we maybe use a debug to switch these on and off?

2023-06-02 01:42 UTC, yhus commented on plugin/scripts/utils/helper.js
> +  saveAppliedJob.style.setProperty('position', 'fixed')
Could maybe set as a const (or just make smaller function call)? 

Is it possible to read it from some kind of configuration?

2023-06-02 01:42 UTC, yhus commented on plugin/scripts/utils/helper.js
> +export const BUTTON_ID = 'virgl-save-job-button'
Rename

2023-06-02 01:42 UTC, yhus commented on plugin/scripts/utils/helper.js
> +
Just curious and not related to this PR, is it possible to animate things (e.g. can we do any kind of valid css operation? )

2023-06-02 01:42 UTC, yhus commented on plugin/scripts/otta.js
> +  const addButtonScript = (location) => {
This seems like it's almost the same as linked? Can refactor out?

2023-06-02 01:42 UTC, yhus commented on plugin/scripts/linkedin.js
> +  const { sendJobInfoToExtension } = await import(chrome.runtime.getURL('scripts/utils/jobBoard.js'))
The first five lines also seem to be almost identical across the three implementations

2023-06-02 01:42 UTC, yhus commented on plugin/scripts/background.js
> +    // todo: probably can have event names as well
Please expand on these two comments - not sure what they mean

2023-06-02 01:42 UTC, yhus commented on plugin/index.html
> +    <h1>Virgl</h1>
Turbocharger

2023-06-02 01:45 UTC, jekiquin commented on plugin/manifest.json
> +  "name": "Virgl Extensions",
Will change

2023-06-02 01:46 UTC, jekiquin commented on plugin/scripts/utils/queries.js
> +  // return Promise.reject(null)
That Promise.reject(null) was for testing. I'm wondering if I can even do a random fail for the getUser function. Or just go with the success as seen on line 20?

2023-06-02 01:49 UTC, jekiquin commented on plugin/scripts/utils/jobBoard.js
> +  console.log('Virgl', response)
Probably not. It can probably get replaced by an alert instead? Basically, I wanted to have some feedback for the user to say that the job was saved. I'm not sure yet what to put it there as a feedback

2023-06-02 01:50 UTC, jekiquin commented on plugin/scripts/utils/helper.js
> +        console.log('Virgl', req.payload)
Same as my comment above. More of feedback for user. But not sure yet what to implement

2023-06-02 01:51 UTC, jekiquin commented on plugin/scripts/background.js
> +    // todo: probably can have event names as well
Will do

2023-06-02 01:54 UTC, jekiquin commented on plugin/scripts/linkedin.js
> +  const { sendJobInfoToExtension } = await import(chrome.runtime.getURL('scripts/utils/jobBoard.js'))
These are all imports statements. The three implementations are content scripts that are injected to the main website. As  ES rules, this is the only way to actually import functions from other files. This one is really weird. I have done a lot of workaround on the other files. Basically all the helper files can't import from each other.

2023-06-02 01:56 UTC, jekiquin commented on plugin/scripts/otta.js
> +  const addButtonScript = (location) => {
Oh yes. Didn't notice that. I thought there would be some difference. I built all of them separately as they all have seemingly specific formatting

2023-06-02 01:57 UTC, jekiquin commented on plugin/scripts/utils/helper.js
> +export const BUTTON_ID = 'virgl-save-job-button'
will do

2023-06-02 01:58 UTC, jekiquin commented on plugin/scripts/utils/helper.js
> +  saveAppliedJob.style.setProperty('position', 'fixed')
for sure. I can have a config for the styling. That probably is the best way. I can even have `styleButton` function

2023-06-02 01:59 UTC, jekiquin commented on plugin/scripts/utils/helper.js
> +
yes. through this `style.setProperty` method, we should be able add any css, including animation. I honestly haven't tried it but on paper, it seems feasible.

2023-06-02 02:00 UTC, jekiquin commented on plugin/index.html
> +    <h1>Virgl</h1>
will change

2023-06-02 04:21 UTC, yhus commented on plugin/scripts/linkedin.js
> +  const { sendJobInfoToExtension } = await import(chrome.runtime.getURL('scripts/utils/jobBoard.js'))
Oh, good point, nm. I was reviewing on my phone so didn't see the entire line 🤦

2023-06-02 04:22 UTC, yhus commented on plugin/scripts/utils/jobBoard.js
> +  console.log('Virgl', response)
I'd recommend moving it to a helper for now, which we/the user can toggle through some kind of debug switch (if on, log to console, if off, stay silent)

2023-06-06 04:51 UTC, yhus approved these changes
Minor issues, but LGTM!

Just a comment re: TODOs, please try to track any TODO by create a ticket, and ideally linking it in the TODO comments.

Otherwise many of these TODOs might just float around for months/years without any action taken.

2023-06-06 04:51 UTC, yhus commented on plugin/scripts/indeed.js
> +    const vjk = urlParams.get('vjk')
Please rename this to something sensible (even though the original dev didn't...)

2023-06-06 04:51 UTC, yhus commented on plugin/scripts/indeed.js
> +    const jk = urlParams.get('jk')
This one too

2023-06-06 04:51 UTC, yhus commented on README.md
> +## Basic Instructions from Chrome
Worth adding a quick snippet on how to build/install this plugin locally?

2023-06-06 15:29 UTC, jekiquin commented
@yhus taking over on this again. Made requested changes

2023-06-06 18:22 UTC, JCPenne commented on plugin/scripts/utils/helper.js
This might be out of scope for this PR. But do we need a button to be injected into the webpage? Would it not be simpler to have a popout dialog box from our extension that also houses a floating button within it?

2023-06-06 18:34 UTC, JCPenne commented on plugin/scripts/indeed.js
> +  const { getImports, createAddButtonScript } = await import('./utils/helper.js')
Does this pull and run the entire utils/helper.js file? Or will it only make requests to the getImports and createAddButtonScript functions? Asking from a performance perspective

2023-06-06 19:23 UTC, jekiquin commented on plugin/scripts/utils/helper.js
Probably have to take this offline coz I'm probably misunderstanding the question :D

2023-06-06 19:27 UTC, jekiquin commented on plugin/scripts/indeed.js
> +  const { getImports, createAddButtonScript } = await import('./utils/helper.js')
I believe it's the same as how we're importing from different packages. The only difference is that with this syntax, it's more of dynamic importing. This is the workaround that we found for importing modules inside content_scripts. But yeah, on paper, it is importing only the necessary functions.

2023-06-06 21:01 UTC, JCPenne approved these changes
LGTM but who the hell knows

2023-06-06 21:09 UTC, merged